name: Docker Image CI

on:
  push:
    branches:
    - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docs:latest
    - name: Authentication to GitHub Packages
      run: docker login docker.pkg.github.com -u nilsme -p ${{ secrets.GITHUB_TOKEN }}
    - name: Push the image to GitHub Packages
      uses: nilsme/docsify_docker@master
      with:
        name: nilsme/docsify_docker/docs:latest
        registry: docker.pkg.github.com
