name: Docker Image CI

on:
  push:
    branches:
    - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docs:latest
    - name: Push the image to GitHub Packages
      run: docker push docs:latest
      
