name: Docker Image CI

on:
  push:
    branches:
    - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docs:$(date +%s)
    - name: Push Docker image to packages
      run: docker push docker.pkg.github.com/nilsme/docsify_docker/:$(date +%s)
